export type Job = {
  id: number;
  title: string;
  pay: number;
  category: string;
};

export type JobCategory = {
  key: string;
  name: string;
  blurb: string;
};

export const categories: JobCategory[] = [
  { key: "lizzyos", name: "LizzyOS Daily", blurb: "Everyday missions inside the garden" },
  { key: "silly", name: "Silly Shifts", blurb: "Quick chaos for quick MB" },
  { key: "explorer", name: "Explorer Tasks", blurb: "Go look at the world a bit" },
  { key: "outdoors", name: "Outdoor Errands", blurb: "Fresh air overtime" },
  { key: "chaos", name: "Chaos Hours", blurb: "Maximum attitude, minimum dignity" },
  { key: "performance", name: "Performance Gigs", blurb: "Stage presence required" },
  { key: "bigleague", name: "Big League Contracts", blurb: "Premium payouts" },
];

const raw: [number, string, number, string][] = [
  [1, "Visit Lizzy's Garden", 14, "lizzyos"],
  [2, "Water one plant", 15, "lizzyos"],
  [3, "Water two plants", 17, "lizzyos"],
  [4, "Water three plants", 17, "lizzyos"],
  [5, "Plant a seed", 17, "lizzyos"],
  [6, "Plant two seeds", 19, "lizzyos"],
  [7, "Check on a plant", 15, "lizzyos"],
  [8, "Grow or collect a flower", 17, "lizzyos"],
  [9, "Window shopping — Open Seed Store", 14, "lizzyos"],
  [10, "Buy any seed", 15, "lizzyos"],
  [11, "Complete Mikhail Quiz", 17, "lizzyos"],
  [12, "Perfect Mikhail Quiz", 20, "lizzyos"],
  [13, "Complete Would Mikael Rather?", 17, "lizzyos"],
  [14, "Perfect Would Mikael Rather?", 20, "lizzyos"],
  [15, "Complete a Crack the Code mission", 19, "lizzyos"],
  [16, "Play Tic-Tac-Toe", 15, "lizzyos"],
  [17, "Beat Mikael at Tic-Tac-Toe", 19, "lizzyos"],
  [18, "Play Heart Catch", 15, "lizzyos"],
  [19, "Complete Lizzy Quiz", 17, "lizzyos"],
  [20, "Play two different games", 19, "lizzyos"],
  [21, "Game Night — 3 different games", 22, "lizzyos"],
  [22, "Claim Daily Reward", 15, "lizzyos"],
  [23, "Protect the streak", 15, "lizzyos"],
  [24, "Check the Token Jar", 14, "lizzyos"],
  [25, "Redeem a token", 17, "lizzyos"],
  [26, "Read Me check-in", 14, "lizzyos"],
  [27, "Visit Our Date", 14, "lizzyos"],
  [28, "Open an Open When letter", 15, "lizzyos"],
  [29, "Check Mission Log", 14, "lizzyos"],
  [30, "Inspect the Recycle Bin", 14, "lizzyos"],
  [31, "Say one nice thing about Mikael", 17, "lizzyos"],
  [32, "Five-minute Hater Break", 17, "lizzyos"],
  [33, "Give Mikael a compliment", 17, "lizzyos"],
  [34, "Laugh at one of Mikael's jokes", 17, "lizzyos"],
  [35, "Drink some water", 15, "lizzyos"],
  [36, "Quick stretch", 15, "lizzyos"],
  [37, "Smile mission", 15, "lizzyos"],
  [38, "Play a favourite song", 15, "lizzyos"],
  [39, "Think about pasta", 14, "lizzyos"],
  [40, "Spot something pink", 15, "lizzyos"],
  [41, "Do one kind thing", 17, "lizzyos"],
  [42, "Send Mikael a nice message", 17, "lizzyos"],
  [43, "Roast Mikael creatively", 17, "lizzyos"],
  [44, "Try to beat a game score", 17, "lizzyos"],
  [45, "Admire the Garden", 14, "lizzyos"],
  [46, "Pick today's favourite flower", 15, "lizzyos"],
  [47, "Token inventory check", 14, "lizzyos"],
  [48, "Think of a future date idea", 17, "lizzyos"],
  [49, "Little Miss Attitude challenge", 17, "lizzyos"],
  [50, "LizzyOS Tour", 19, "lizzyos"],

  [51, "🏆 Do 10 dramatic victory jumps for absolutely no reason.", 30, "silly"],
  [52, "🕺 Walk across the room like you're on a fashion runway.", 28, "silly"],
  [53, "🤪 Make your weirdest face.", 25, "silly"],
  [54, "🧸 Give your favourite stuffed animal, person, or object a name.", 26, "silly"],
  [55, "🧑‍🎤 Recreate a celebrity pose.", 27, "silly"],
  [56, "👑 Wear something as a crown.", 25, "silly"],
  [57, "🧻 Put toilet paper on your head.", 25, "silly"],
  [58, "🧍‍♀️ Freeze like a statue for 30 seconds while someone tries to make you laugh.", 31, "silly"],
  [59, "🥶 Hold something cold to your cheek for 20 seconds.", 29, "silly"],
  [60, "🪴 Give a plant a name.", 26, "silly"],

  [61, "🎨 Draw a terrible picture of Mikael.", 27, "explorer"],
  [62, "📖 Open a random book and send the first sentence you see.", 24, "explorer"],
  [63, "🌍 Take a photo of something that starts with M.", 24, "explorer"],
  [64, "👀 Take a photo of something you walk past every day but never notice.", 25, "explorer"],
  [65, "🍃 Pick up one piece of litter.", 26, "explorer"],
  [66, "🪞 Give yourself a compliment in the mirror.", 25, "explorer"],
  [67, "💌 Send Mikael a completely unnecessary compliment.", 26, "explorer"],
  [68, "🌸 Find a pretty flower.", 23, "explorer"],
  [69, "🐦 Take a photo of a bird. Bonus points if it looks angry.", 26, "explorer"],
  [70, "☁️ Find a cloud that looks like something.", 24, "explorer"],

  [71, "🌳 Hug a tree.", 24, "outdoors"],
  [72, "😈 Annoy your sister — then apologise immediately.", 29, "outdoors"],
  [73, "🪞 Take a dramatic selfie.", 23, "outdoors"],
  [74, "🧦 Wear two different socks.", 22, "outdoors"],
  [75, "🥤 Drink a glass of water.", 23, "outdoors"],
  [76, "🐱 Find an animal.", 23, "outdoors"],
  [77, "🌅 Take a photo of the sky. Pretty points awarded.", 23, "outdoors"],
  [78, "😂 Send Mikael your best meme. Make him laugh.", 26, "outdoors"],
  [79, "🧸 Hug something unnecessarily large.", 25, "outdoors"],
  [80, "🎵 Send Mikael the song currently stuck in your head.", 24, "outdoors"],

  [81, "👟 Put your shoes on the wrong feet.", 22, "chaos"],
  [82, "😎 Take a selfie without smiling. Maximum attitude.", 22, "chaos"],
  [83, "🍫 Find the best snack in your house. Photo + explanation.", 25, "chaos"],
  [84, "❤️ Send someone a random \"hope you're having a good day.\"", 25, "chaos"],
  [85, "📸 Take a photo of something pink.", 22, "chaos"],
  [86, "🌿 Touch some grass — literally.", 22, "chaos"],
  [87, "🐌 Find something moving slower than you.", 24, "chaos"],
  [88, "🧦 Put a sock on your hand and introduce your new friend.", 25, "chaos"],
  [89, "📱 Change your wallpaper for 5 minutes. It must be ridiculous.", 26, "chaos"],
  [90, "🥱 Take a fake \"I just woke up\" selfie. Maximum chaos.", 23, "chaos"],

  [91, "🗣️ Talk like a duck for 30 seconds.", 29, "performance"],
  [93, "📖 Read the first sentence of a random book dramatically.", 28, "performance"],
  [94, "🪑 Sit somewhere you're not supposed to sit.", 25, "performance"],
  [95, "🪴 Compliment a plant. 😂", 27, "performance"],
  [96, "🧊 Put one ice cube in your hand and see how long you last.", 29, "performance"],
  [97, "🧍 Give yourself a motivational speech.", 28, "performance"],
  [98, "🐸 Do your best animal impression.", 29, "performance"],
  [99, "🤨 Take the most suspicious-looking selfie possible.", 26, "performance"],
  [100, "🧸 Name a random object and introduce it to Mikael.", 28, "performance"],

  [101, "🎨 The Artist", 68, "bigleague"],
  [102, "🗣️ The Accent Challenge", 73, "bigleague"],
  [103, "🏆 The Paper Airplane Olympics", 70, "bigleague"],
  [104, "🌍 The Floor Is Lava", 66, "bigleague"],
  [105, "😂 Make Your Sister Laugh", 65, "bigleague"],
  [106, "🧑‍🍳 The Weird Snack Chef", 68, "bigleague"],
  [107, "🔤 Backwards Alphabet", 71, "bigleague"],
  [108, "🎤 Terrible Singer", 63, "bigleague"],
  [109, "🕵️ The Great Hide & Seek", 66, "bigleague"],
  [110, "🧍 Flamingo Stand", 46, "bigleague"],
  [111, "🥄 Spoon Nose", 48, "bigleague"],
  [112, "🐸 Frog Impression", 50, "bigleague"],
  [113, "🐧 Penguin Walk", 48, "bigleague"],
  [114, "🕺 Worst Dance Move", 46, "bigleague"],
  [115, "💃 10-Second Dance Party", 43, "bigleague"],
  [116, "🪞 Mirror Stare-Down", 50, "bigleague"],
  [117, "🗣️ Responsible Adult", 53, "bigleague"],
  [118, "😂 One-Sentence Comedian", 53, "bigleague"],
  [119, "🚪 Movie Entrance", 48, "bigleague"],
];

export const jobs: Job[] = raw.map(([id, title, pay, category]) => ({ id, title, pay, category }));
